name-template: 'Release v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
version-template: '$MAJOR.$MINOR'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

template: |
  ## What's Changed

  $CHANGES
