# this jinja2 template is filled out by process.py to build mkdocs.yml
site_name: Use Case Library v1.0
site_url: https://cfde-usecases.readthedocs-hosted.com/en/latest/

copyright: 'This website is available under the terms of the
<a href="https://creativecommons.org/licenses/by/4.0/">CC-BY license</a>.<br />
To contribute or open an issue, visit the
<a href="https://github.com/dcppc/use-case-library">dcppc/use-case-library</a>
GitHub repository.
<br />'

nav:
  - Introduction: index.md
  - Use Cases:
{% for obj in yield_objects('USE CASE') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Objectives:
{% for obj in yield_objects('OBJECTIVE') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Personas:
{% for obj in yield_objects('PERSONA') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Tasks:
{% for obj in yield_objects('TASK') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Requirements:
{% for obj in yield_objects('REQUIREMENT') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Complete List of Contents: full_list.md
  - Glossary of Terms: glossary.md
  - Contributing Guide : CONTRIBUTING.md
  - Code of Conduct : CODEOFCONDUCT.md
  - License : LICENSE.md

theme:
  name: material
  palette:
    primary: white
  features:
    - navigation.tabs
    - navigation.instant
  logo: ./images/CFDE-logo.png
docs_dir: docs

extra_css:
  - stylesheets/extra.css
