# this jinja2 template is filled out by process.py to build mkdocs.yml
site_name: CFDE Use Case Library
site_url: https://nih-cfde.github.io/use-case-library-build/

copyright: 'To contribute or open an issue, visit
#<a href="https://github.com/nih-cfde/use-case-library-build">Use Case</a> repository'


nav:
  - Introduction: index.md
  - Use Cases:
{% for obj in yield_objects('USE CASE') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Objectives:
{% for obj in yield_objects('OBJECTIVE') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Personas:
{% for obj in yield_objects('PERSONA') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Tasks:
{% for obj in yield_objects('TASK') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Requirements:
{% for obj in yield_objects('REQUIREMENT') %}
    - {{ obj.title }}: {{ obj.ident }}.md
{% endfor %}
  - Complete List of Contents: full_list.md
  - Glossary of Terms: glossary.md
  - Contributing Guide : CONTRIBUTING.md
  - Code of Conduct : CODEOFCONDUCT.md
  - License : LICENSE.md

theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.tabs
    - navigation.instant
  logo: ./images/CFDE-logo.png
  favicon: ./images/CFDE-logo-white-outline.png
  docs_dir: docs
  custom_dir: custom


extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:CFDE-HelpDesk%20<support@cfde.atlassian.net>
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CfdeNih
    - icon: fontawesome/brands/github
      link: https://github.com/nih-cfde/use-case-library-build

extra_css:
  - stylesheets/extra.css
