channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - mkdocs=1.1.2
    - snakemake-minimal=5.20.1
    - pip
    - pip:
      - mkdocs-material
      - mkdocs-git-revision-date-localized-plugin
      - mkdocs-htmlproofer-plugin
      - mkdocs-awesome-pages-plugin
